services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userhub
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db